[project]
name = "the-recipes-ai"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.49.0",
    "pydantic>=2.12.4",
]

[tool.setuptools]
py-modules = [
    "main",
    "generate"
]
